version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/studentdataapp
    overwrite: true
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 600
      runas: root
  AfterInstall:
    - location: after_install.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: application_start.sh
      timeout: 600
      runas: root
